name: Compile, test and check format

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install --immutable

      - name: Compile package
        run: yarn compile

      - name: Test the package
        run: yarn test

      # - name: Check file formatting
      #   run: yarn format:check
